// Code generated by "stringer -type=Operator"; DO NOT EDIT.

package tree

import "strconv"

const _Operator_name = "ConcatenationUnionStarPlus"

var _Operator_index = [...]uint8{0, 13, 18, 22, 26}

func (i Operator) String() string {
	if i < 0 || i >= Operator(len(_Operator_index)-1) {
		return "Operator(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Operator_name[_Operator_index[i]:_Operator_index[i+1]]
}
